### ISSUE TITLE
Policy not evaluated correctly when statements are not in order within comprehensions

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#101]
This is similar to #97.
I came across this when trying to break the statement scheduling in Regorus, while using OPA and rego-cpp for comparison.

```rego
package test

x = y {
	y = [z |
		z = a[_]
		a = [1, 2, 3]
	]
}
```

evaluates to `x = []` instead of `x = [1, 2, 3]`

It seems like the topological sorting added in #98  does not extend into comprehensions.

**Comment by matajoh** [comment]
Thanks for another great find. Intriguingly, this was actually due to overzealous capture logic for implicit enums. Whatever the cause, I appreciate the report!
