### ISSUE TITLE
Performance issue with small policy

### ISSUE THREAD

**Issue by fernape** [microsoft/rego-cpp#131]
We are using `rego-cpp` to evaluate a small policy with also a small input.

The input contains a `role` a `resource` and an `action` requested on that resource.

The policy extracts those values from the input and finds the role in the `roles` array.
If found, then it tries to match any of the resource-action pairs associated with that role and see if any of those match the resource and action required in the input.

In the response, the policy returns the whole list of grants (`Grants`) due to the role the user is logged in as.

When running this policy and input with the `rego` CLI it takes over a second to evaluate:
```
time ./rego -d repro/policy -i repro/input -q data.rules.response
rego 0.3.11 (main:cb96763, Wed, 24 Jan 2024 11:22:12 +0000)[GNU 11.4.0] on linux
{"Response":[{"Decision":"Permit", "Grants":[{"action":"create", "resource":"Material"}, {"action":"create", "resource":"Resource1"}, {"action":"delete", "resource":"Material"}, {"action":"delete", "resource":"Resource1"}, {"action":"read", "resource":"Material"}, {"action":"read", "resource":"Resource1"}, {"action":"read", "resource":"Resource2"}, {"action":"update", "resource":"Material"}, {"action":"update", "resource":"Resource1"}], "Missing attributes":[], "Status":{"StatusCode":{"Value":"urn:oasis:names:tc:xacml:1.0:status:ok"}}}]}

real    0m1.112s
user    0m1.093s
sys     0m0.008s
```
Changing the `role-ids` in the input to something unknown like `XXX` still takes more than 800 ms:

```
time ./rego -d repro/policy -i repro/input -q data.rules.response
rego 0.3.11 (main:cb96763, Wed, 24 Jan 2024 11:22:12 +0000)[GNU 11.4.0] on linux
{"Response":[{"Decision":"Deny", "Grants":[], "Missing attributes":[], "Status":{"StatusCode":{"V
[policy.txt](https://github.com/microsoft/rego-cpp/files/15126800/policy.txt)
[input.txt](https://github.com/microsoft/rego-cpp/files/15126801/input.txt)
alue":"urn:oasis:names:tc:xacml:1.0:status:ok"}}}]}

real    0m0.809s
user    0m0.804s
sys     0m0.004s
```

Our policy would grow in time with more pairs resource-action and more roles, but since the policy is evaluated multiple times in different scenarios it would be difficult to use if the evaluation time also grows.
Is it possible to do something in the policy (rewrite some parts) to speed the evaluation up?

Thanks

**Comment by anakrish** [comment]
What system are you running on? On my machine it takes about 64 milliseconds, which is still on the higher side when compared to OPA (25 millis) and regorus (4 millis).

> Is it possible to do something in the policy (rewrite some parts) to speed the evaluation up?

What is your usecase? Are you planning to evaluate policies using the command line or in-process by using the library.

**Comment by fernape** [comment]
No build type was specified so I suppose it was in Debug mode then:
```
 grep CMAKE_BUILD_TYPE CMakeCache.txt 
CMAKE_BUILD_TYPE:STRING=
```
So I build with CMAKE_BUILD_TYPE=Release and g++ 11.4:
```
 egrep 'CMAKE_CXX_COMPILER:FILEPATH|CMAKE_BUILD_TYPE' CMakeCache.txt 
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
```
And run the test again:
```
 time ./rego -d repro/policy.txt -i repro/input.txt -q data.rules.response
rego 0.3.11 (main:cb96763, Wed, 24 Jan 2024 11:22:12 +0000)[GNU 11.4.0] on linux
{"Response":[{"Decision":"Permit", "Grants":[{"action":"create", "resource":"Material"}, {"action":"create", "resource":"Resource1"}, {"action":"delete", "resource":"Material"}, {"action":"delete", "resource":"Resource1"}, {"action":"read", "resource":"Material"}, {"action":"read", "resource":"Resource1"}, {"action":"read", "resource":"Resource2"}, {"action":"update", "resource":"Material"}, {"action":"update", "resource":"Resource1"}], "Missing attributes":[], "Status":{"StatusCode":{"Value":"urn:oasis:names:tc:xacml:1.0:status:ok"}}}]}

real    0m0.257s
user    0m0.226s
sys     0m0.008s
```
This is much better, thanks.

**Comment by fernape** [comment]
> > The use case is evaluating policies using the library.
> 
> Great. I'd suggest the following guidelines that will work with most Rego implementations:
> 
>     * Load the policies into the engine once and evaluate queries multiple times instead of loading the policies again and again for each query. This is possible only if the implementation is used as a library or as a daemon.

Already doing this!

> 
>     * If performing lookups, prefer objects and sets over arrays when possible. With small number of items, it won't matter that much. But with large number of items, objects and sets will perform better than arrays.
> 
>     * Preprocess data to cache operations that evaluate to the same value in each query. Rewrite rules to perform lookups on preprocessed data. The rules in such a rewritten policy typically are typically more declarative and readable.
>       Say your policy is written as follows.
>       ```rego
>       package example
>       import future.keywords
>       
>       values := [1, 2, 3]
>       allow if {
>          some i in values  # For each query `values` is processed again
>          some j in values
>          # Check whether input contains an allowed pair.
>          input.pair == [i, j]
>       }
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       Then for each query evaluation, the `values` will be processed again to generate pairs which are then compared with input.
>       Many rego engines may not be able to optimize this.
>       For better performance and scalability (and possibly better readability),  you could rewrite the policy as below:
>       ```rego
>       package example
>       import future.keywords
>       
>       values := [1, 2, 3]
>       
>       # define a rule that preprocesses data and creates lookup tables
>       preprocess := {
>         "allowed_pairs" : { [i,j] |
>               some i in values
>               some j in values
>           },
>           # Other preprocessing 
>       }
>       
>       allow if {
>          # Perform lookup on precomputed data
>          input.pair in data.allowed_pairs
>       }
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       With such a rewritten policy, you'd do the following setup once to initialize the policy evaluator
>       ```
>            load_policy();
>            preprocessed_data = eval_rule("preprocess")
>            set_data(preprocessed_data);
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       Now you can evaluate queries as before. They will be much faster since they will perform lookups instead of computations.

That's very helpful,

Thanks!
