### ISSUE TITLE
rego-cpp binaries are large

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#132]
On x86-64 Ubuntu, even after `strip`, the rego binary created using GCC is 16M. When created using clang, after `strip` it is 6.5 MB.
```shell
anakrish@ubu ~/r/r/build (main)> tree -sh dist/bin
[4.0K]  dist/bin
├── [ 16M]  rego
├── [ 18M]  rego_test
├── [ 16M]  rego_trieste
└── [ 18M]  yaml_trieste

```

On OSX running Apple Silicon, the rego binary is `18M` after strip.
```
anand@Anands-M3Max ~/r/r/build (main)> tree -sh dist/bin
[ 192]  dist/bin
├── [ 18M]  rego
├── [ 22M]  rego_test
├── [ 21M]  rego_trieste
└── [ 22M]  yaml_trieste
```

**Comment by matajoh** [comment]
We're aware of the binary size issue. It is common across all Trieste-based solutions at the moment. We're working to solve it upstream.
