### ISSUE TITLE
Not possible to use tools like heaptrack to analyze memory usage 

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#133]
rego-cpp takes a hard-dependency on `snmalloc`. As a result, it is not possible to use tools like [heaptrack](https://github.com/KDE/heaptrack) to analyze memory usage.

Having a way to use the default glibc memory allocator instead of snmalloc would make it easier to analyze memory usage.

**Comment by matajoh** [comment]
This is a Trieste issue, I've filed an issue for it: https://github.com/microsoft/Trieste/issues/116
