### ISSUE TITLE
Failure parsing json

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#152]
The attached file results in invalid nodes error.
[large.json](https://github.com/user-attachments/files/15897090/large.json)

```
> bin/rego -i large.json 1
rego 0.4.0 (HEAD:cfabe01, Tue, 18 Jun 2024 11:52:24 +0100)[Clang 14.0.0] on linux
High incidence of invalid nodes from parser: 3070 of 3206 tokens in first 4096 bytes
Invalid input file: /home/anakrish/repos/rego-compare/large.json
```

**Comment by matajoh** [comment]
That file is almost purpose-built to defeat the heuristic Trieste uses to detect whether a file is a valid input for a pipeline. This needs some thought. In the meantime, this is an excellent test case.
