### ISSUE TITLE
rego-cpp throws when opa has no issues

### ISSUE THREAD

**Issue by ivarprudnikov** [microsoft/rego-cpp#52]
I'm using a locally built rego cpp interpreter but it throws an error instead of returning the expected value `false` for a given query.

Example

- `policy.demo.rego`:

    ```
    package demo
    import future.keywords.if
    default allow := false
    allow if {
	    count(trim_space(input.foo)) > 0
    }
    ```

- `input.demo.json`:

    ```
    { "bar": "baz" }
    ```

The following query **would throw**:

```
./bin/rego_interpreter -d policy.demo.rego -i input.demo.json -q data.demo.allow

rego_interpreter: /home/ubuntu/demo/src/unifier.cc:1248: std::optional<RankedNode> rego::UnifierDef::resolve_rulefunc(const trieste::Node &, const trieste::Nodes &): Assertion `rulefunc->type() == RuleFunc' failed.
Aborted
```

Whilst the regular https://play.openpolicyagent.org/ has no issues with evaluating, equally the [opa cli](https://www.openpolicyagent.org/docs/latest/#running-opa) works with the following results:

```
./opa eval data.demo.allow --data policy.demo.rego --input input.demo.json

{
  "result": [
    {
      "expressions": [
        {
          "value": false,
          "text": "data.demo.allow",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

The expectation is that the query should not fail due to a missing key (most likely) in the input.

**Comment by matajoh** [comment]
This is resolved as of 0.3.0.
