### ISSUE TITLE
wrappers-c CI doesn't work for PRs from forks

### ISSUE THREAD

**Issue by mjp41** [microsoft/rego-cpp#71]
The CI assumes that the main repo contains the commit hash, but that is not the case if the PR is from a fork.  See:

https://github.com/microsoft/rego-cpp/actions/runs/6131481980/job/16641498869?pr=70#step:4:31

**Comment by mjp41** [comment]
Actually, this seems like you need to update the commit ID and remote for each PR.

**Comment by mjp41** [comment]
Perhaps, this should take variables from CMake that are set by the CI:

* GITHUB_REF
* GITHUB_REPOSITORY

https://docs.github.com/en/actions/learn-github-actions/variables

They look like they could get the PRs branch nicely.

**Comment by matajoh** [comment]
Fixed in #73
