### ISSUE TITLE
Failed test for main

### ISSUE THREAD

**Issue by mjp41** [microsoft/rego-cpp#72]
The following test fails on `main`:

```
 ./rego_trieste test -f --seed 3109230158
```

Uncovered in my PR (https://github.com/microsoft/rego-cpp/actions/runs/6131481980/job/16641498709?pr=70#step:5:64), but this failed on main when I tried it.

**Comment by mjp41** [comment]
This looks related failure:
```
./rego_trieste "test" "-f" --seed 3166257874
```

This is from a different PR (https://github.com/microsoft/rego-cpp/actions/runs/6139291462/job/16657047458?pr=73#step:5:63)

**Comment by matajoh** [comment]
1355977544
