### ISSUE TITLE
Policy is not evaluated correctly when statements are not in order

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#97]
```rego
package test

x = y {
 y = z
 z = 12
}
```

x is evaluated to {} instead of 12.

**Comment by matajoh** [comment]
Thank you so much for finding this issue! This is a regression we unknowingly added during an optimization pass which was subsequently missed by both ours and OPAs test suites! I've added this explicitly as a regression test to the regocpp test suite.

**Comment by anakrish** [comment]
@matajoh Glad to be of help.

>  was subsequently missed by both ours and OPAs test suites!

While working on [Regorus](https://github.com/microsoft/regorus), we realized that the OPA test-suites may not cover all the semantics of Rego. Hence, we have been working on adding local tests to lock down behavior.
